FROM node:alpine
ARG GITHUB_TOKEN
ARG SUPABASE_DB
ARG JWT_SECRET
ARG BETTER_AUTH_SECRET
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG GH_CLIENT_ID
ARG GH_CLIENT_SECRET
ARG CHAPA_SECRET_KEY
ARG CLOUDINARY_SECRET
ARG CLOUDINARY_API_KEY
ARG CLOUDINARY_CLOUD_NAME
ARG BREVO
ARG CLOUDNAME
ARG TELEBIRR_MERCHANT_ID
ARG FABRIC_APP_ID
ARG SHORT_CODE
ARG APP_SECRET
ARG TELEBIRR_PRIVATE_KEY
ARG TB_BASE_URL
ARG WEB_BASE_URL
ARG FRONTEND_URL
ARG API_BASE_URL
ARG JWT_ISSUER

ENV GITHUB_TOKEN=${GITHUB_TOKEN} \
SUPABASE_DB=${SUPABASE_DB}\
JWT_SECRET=${JWT_SECRET}\
BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}\
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}\
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}\
GH_CLIENT_ID=${GH_CLIENT_ID}\
GH_CLIENT_SECRET=${GH_CLIENT_SECRET}\
CHAPA_SECRET_KEY=${CHAPA_SECRET_KEY}\
CLOUDINARY_SECRET=${CLOUDINARY_SECRET}\
CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}\
CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}\
BREVO=${BREVO}\
CLOUDNAME=${CLOUDNAME}\
TELEBIRR_MERCHANT_ID=${TELEBIRR_MERCHANT_ID}\
FABRIC_APP_ID=${FABRIC_APP_ID}\
SHORT_CODE=${SHORT_CODE}\
APP_SECRET=${APP_SECRET}\
TELEBIRR_PRIVATE_KEY=${TELEBIRR_PRIVATE_KEY}\
TB_BASE_URL=${TB_BASE_URL}\
WEB_BASE_URL=${WEB_BASE_URL}\
FRONTEND_URL=${FRONTEND_URL}\
API_BASE_URL=${API_BASE_URL}\
JWT_ISSUER=${JWT_ISSUER}

COPY ./package.json .
COPY ./prisma /prisma
RUN npm install
COPY . .
RUN npx prisma db push
RUN tsc
EXPOSE 1000
CMD ["node", "/dist/index.js"]

