name: CD - Build and deploy
on:
  push:
    branches:
      -main
    paths:
      - "**"
      - "!**.md"
      - "!**.yml"
  pull-request:
    branches:
      -main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: install dependencies
        run: npm install
      - name: build
        run: |
          npx prisma db push
          npx tsx
          
